export const DIAMONDS_ADDED_RARECARET = 'DIAMONDS_ADDED_RARECARET'
export const COUNT_CHANGED = 'CARAT_CHANGED'
export const DIAMONDS_ADDED_IDEX = 'DIAMONDS_ADDED_IDEX'
export const NEW_MATCH = 'NEW_MATCH'